# NumPy Notes

## NumPy

NumPy is a Python library for numerical computing.  
Its core data structure is the multidimensional `ndarray`.

## Dimensions

NumPy arrays can have different numbers of dimensions:

1. **1D array**
2. **2D array**
3. **3D array**
4. **nD array** — any number of dimensions

Example:

```python
# 1D
[1, 2, 3]

# 2D
[[1, 2],
 [3, 4]]
```

> Note: 1D, 2D, 3D, etc. are not separate NumPy data types. They describe the number of dimensions (`ndim`) of an `ndarray`.

---

## Why Use NumPy Instead of Python Lists?

### 1. Homogeneous Data

NumPy arrays are generally **homogeneous**, meaning their elements are stored using a single data type (`dtype`).

For example:

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)
```

Using a fixed data type reduces memory overhead and allows NumPy to process numerical data efficiently.

### 2. Contiguous Memory

A typical NumPy array stores its data in a **contiguous memory buffer**.

A Python list, on the other hand, is an array of references/pointers to Python objects. The objects being referenced may be located elsewhere in memory.

| Python List | NumPy Array |
|---|---|
| Stores references to Python objects | Stores homogeneous array data |
| Referenced objects may be scattered in memory | Data is typically stored contiguously |
| More memory overhead | More memory efficient for numerical data |

Contiguous storage provides better **memory locality** and can improve CPU cache utilization.

### 3. Vectorization

NumPy allows operations to be performed on entire arrays without explicitly writing Python loops.

Example:

```python
import numpy as np

a = np.array([1, 2, 3, 4])

print(a * 2)
```

Output:

```text
[2 4 6 8]
```

This is called **vectorization**.

### 4. SIMD

NumPy's optimized low-level operations can use **SIMD (Single Instruction, Multiple Data)** where supported.

SIMD allows a single CPU instruction to operate on multiple data values at the same time.

### 5. Efficient CPU Cache Utilization

Because NumPy arrays can store data contiguously, the CPU can access nearby elements efficiently.

This improves **memory locality** and can make numerical operations faster.

---

## Key Takeaways

- NumPy is mainly used for **numerical computing**.
- Its core data structure is the **multidimensional `ndarray`**.
- NumPy arrays are generally **homogeneous**.
- NumPy can store numerical data efficiently in contiguous memory.
- **Vectorization** reduces the need for explicit Python loops.
- NumPy can take advantage of **SIMD** and efficient CPU cache usage.
- NumPy is generally much more efficient than Python lists for large-scale numerical operations.


---

## Basic NumPy Array Operations

### Creating Arrays

```python
import numpy as np

a = np.array([1, 3, 5])
b = np.array([1, 2, 3])
```

### Array Multiplication

NumPy arrays support element-wise arithmetic operations.

```python
a * b
```

Output:

```text
[1 6 15]
```

### Array Replacement

NumPy arrays can be modified using indexing.

```python
a[1] = 6
```

Now:

```text
[1 6 5]
```

### Important NumPy Functions

- `np.array()` — creates a NumPy array
- `np.arange()` — creates an array with a range of values
- `np.zeros()` — creates an array filled with zeros
- `np.ones()` — creates an array filled with ones
- `np.reshape()` — changes the shape of an array without changing its data

---

## NumPy and Mathematics

NumPy is widely used in mathematical and numerical applications.

It provides efficient operations for:

- Addition and subtraction
- Multiplication and division
- Mean, sum, minimum and maximum
- Matrix operations
- Statistical calculations
- Random number generation

---

## Applications of NumPy

NumPy is commonly used as a foundation for:

- **Mathematics**
- **Python programming**
- **Data Analysis**
- **Backend/Data processing**
- **Digital Photography / Image Processing**
- **Machine Learning**

Many popular Python libraries used in Data Science and Machine Learning build on or work closely with NumPy.

---


In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)

array([1, 2, 3])

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [10]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)
