# NumPy Notes

## NumPy

NumPy is a Python library for numerical computing.  
Its core data structure is the multidimensional `ndarray`.

## Dimensions

NumPy arrays can have different numbers of dimensions:

1. **1D array**
2. **2D array**
3. **3D array**
4. **nD array** — any number of dimensions

Example:

```python
# 1D
[1, 2, 3]

# 2D
[[1, 2],
 [3, 4]]
```

> Note: 1D, 2D, 3D, etc. are not separate NumPy data types. They describe the number of dimensions (`ndim`) of an `ndarray`.

---

## Why Use NumPy Instead of Python Lists?

### 1. Homogeneous Data

NumPy arrays are generally **homogeneous**, meaning their elements are stored using a single data type (`dtype`).

For example:

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)
```

Using a fixed data type reduces memory overhead and allows NumPy to process numerical data efficiently.

### 2. Contiguous Memory

A typical NumPy array stores its data in a **contiguous memory buffer**.

A Python list, on the other hand, is an array of references/pointers to Python objects. The objects being referenced may be located elsewhere in memory.

| Python List | NumPy Array |
|---|---|
| Stores references to Python objects | Stores homogeneous array data |
| Referenced objects may be scattered in memory | Data is typically stored contiguously |
| More memory overhead | More memory efficient for numerical data |

Contiguous storage provides better **memory locality** and can improve CPU cache utilization.

### 3. Vectorization

NumPy allows operations to be performed on entire arrays without explicitly writing Python loops.

Example:

```python
import numpy as np

a = np.array([1, 2, 3, 4])

print(a * 2)
```

Output:

```text
[2 4 6 8]
```

This is called **vectorization**.

### 4. SIMD

NumPy's optimized low-level operations can use **SIMD (Single Instruction, Multiple Data)** where supported.

SIMD allows a single CPU instruction to operate on multiple data values at the same time.

### 5. Efficient CPU Cache Utilization

Because NumPy arrays can store data contiguously, the CPU can access nearby elements efficiently.

This improves **memory locality** and can make numerical operations faster.

---

## Key Takeaways

- NumPy is mainly used for **numerical computing**.
- Its core data structure is the **multidimensional `ndarray`**.
- NumPy arrays are generally **homogeneous**.
- NumPy can store numerical data efficiently in contiguous memory.
- **Vectorization** reduces the need for explicit Python loops.
- NumPy can take advantage of **SIMD** and efficient CPU cache usage.
- NumPy is generally much more efficient than Python lists for large-scale numerical operations.


---

## Basic NumPy Array Operations

### Creating Arrays

```python
import numpy as np

a = np.array([1, 3, 5])
b = np.array([1, 2, 3])
```

### Array Multiplication

NumPy arrays support element-wise arithmetic operations.

```python
a * b
```

Output:

```text
[1 6 15]
```

### Array Replacement

NumPy arrays can be modified using indexing.

```python
a[1] = 6
```

Now:

```text
[1 6 5]
```

### Important NumPy Functions

- `np.array()` — creates a NumPy array
- `np.arange()` — creates an array with a range of values
- `np.zeros()` — creates an array filled with zeros
- `np.ones()` — creates an array filled with ones
- `np.reshape()` — changes the shape of an array without changing its data

---

## NumPy and Mathematics

NumPy is widely used in mathematical and numerical applications.

It provides efficient operations for:

- Addition and subtraction
- Multiplication and division
- Mean, sum, minimum and maximum
- Matrix operations
- Statistical calculations
- Random number generation

---

## Applications of NumPy

NumPy is commonly used as a foundation for:

- **Mathematics**
- **Python programming**
- **Data Analysis**
- **Backend/Data processing**
- **Digital Photography / Image Processing**
- **Machine Learning**

Many popular Python libraries used in Data Science and Machine Learning build on or work closely with NumPy.

---


In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)

array([1, 2, 3])

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# get size
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [9]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [10]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
#get type
import numpy as np
a = np.array([1, 2, 3], dtype=np.int32)
a.dtype


dtype('int32')

In [13]:
#get size
a.itemsize

4

In [9]:
#get total size
a.size * a.itemsize

12

# Accessing/Changing specific elements. rows, columns, etc

In [14]:
a = np.array([[1, 2, 3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get specific element [row, column]
print(a[1, 5])
#print(a[1, -2]) #negative indexing

13


In [16]:
#get specific row
a[0, :] #first row

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#get specific column
a[:, 2] #third column

array([ 3, 10])

In [18]:
#getting a little more advanced[startindex:endindex:stepsize]
a[0, 1:6:2] #first row, from index 1 to 5, with step size of 2

array([2, 4, 6])

In [24]:
a[1,5] = 20 #changing value of specific element
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3D**

In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [ ]:
#replace
b[:,1, :]

array([[3, 4],
       [7, 8]])

In [44]:
b[:1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [46]:
b

array([[[9, 9],
        [8, 8]],

       [[5, 6],
        [7, 8]]])

# Initializing different types of Array

In [45]:
# All zero matrix
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [48]:
# All 0s matrix
np.zeros((2,3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [51]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [53]:
#Any othee number (full_like)
np.full_like(a.shape, 4)

array([4, 4])

In [54]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand((4,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [57]:
np.random.rand(4,2) #random number between 0 and 1

array([[0.86553675, 0.82054365],
       [0.310004  , 0.92298542],
       [0.96664499, 0.33594882],
       [0.3345403 , 0.15031329]])

In [59]:
np.random.random_sample(a.shape)

array([[0.01492291, 0.28116402, 0.05816098, 0.28924913, 0.52617511,
        0.27923111, 0.06577129],
       [0.52490368, 0.37828681, 0.92245733, 0.49927132, 0.38383367,
        0.62765652, 0.97689696]])

In [63]:
# Random integers
np.random.randint(-4, 8, size=(3,3))

array([[-2,  7, -2],
       [-3,  7,  3],
       [ 0,  4, -4]], dtype=int32)

In [ ]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r1 = np.reshape(arr,(3,2), axis=1)
print(r1)

TypeError: reshape() got an unexpected keyword argument 'axis'

In [68]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# Mathematics

In [72]:
a = np.array([1, 2, 3,4])
print(a)

[1 2 3 4]


In [73]:
a + 2

array([3, 4, 5, 6])

In [74]:
a -2

array([-1,  0,  1,  2])

In [75]:
a * 2


array([2, 4, 6, 8])

In [76]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [77]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [78]:
a ** 2

array([ 1,  4,  9, 16])

In [79]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [80]:
# Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra


In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])